CREATE TABLE IF NOT EXISTS PLAYER (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR
);

CREATE TABLE IF NOT EXISTS MANCALA (
    ID INT NOT NULL AUTO_INCREMENT,
    PLAYER1_ID INTEGER,
    PLAYER2_ID INTEGER,
    PLAYER1_SCORE TINYINT,
    PLAYER2_SCORE TINYINT,
    STATE TINYINT ARRAY
);

DROP TABLE PLAYER;
DROP TABLE MANCALA;

CREATE TABLE PLAYER (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR
);

CREATE TABLE MANCALA (
    ID INT NOT NULL AUTO_INCREMENT,
    PLAYER1_ID INTEGER,
    PLAYER2_ID INTEGER,
    PLAYER1_SCORE TINYINT,
    PLAYER2_SCORE TINYINT,
    STATE TINYINT ARRAY
);

INSERT INTO PLAYER (NAME) VALUES ('Mike');
INSERT INTO PLAYER (NAME) VALUES ('Laura');

INSERT INTO MANCALA (PLAYER1_ID, PLAYER2_ID, PLAYER1_SCORE, PLAYER2_SCORE, STATE)
            VALUES (1, 2, 0, 0, ARRAY[6,6,6,6,6,6,6,6,6,6,6,6] );








